# Setup
title:        MR-Hub
tagline:      Open-access software tools for the ISMRM community
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
